catalog/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    path('list/', views.listing, name='list'),
    url(r'^(?P<game_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^search/$', views.search, name='search'),
    path('results/<int:game_id>/', views.listingResultbyGame, name='listresult'),
    path('addResult/', views.addResult, name='addResult'),
]

game/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url

urlpatterns = [
    url(r'^catalog/', include(('catalog.urls', 'catalog'), namespace='catalog')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

catalog/models.py
from django.db import models


class Console(models.Model):
    name = models.CharField(max_length=200, unique=True)
    def __str__(self):
    	return self.name

class Player(models.Model):
    email = models.EmailField(max_length=100)
    name = models.CharField(max_length=200)
    def __str__(self):
    	return self.name

class Game(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    available = models.BooleanField(default=True)
    title = models.CharField(max_length=200)
    picture = models.URLField()
    consoles = models.ManyToManyField(Console, related_name='games', blank=True)
    def __str__(self):
    	return self.title

class Result(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    score = models.IntegerField(null=True)
    level = models.CharField(max_length=50)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    player = models.ForeignKey(Player, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
    	if 5000 < self.score <= 10000:
        	self.level = 'Advanced'
    	elif self.score > 10000:
        	self.level = 'Expert'
    	else:
    		self.level = 'Beginner'
    	super(Result, self).save(*args, **kwargs)  # Call the "real" save() method.


    def __str__(self):
    	return str(self.score)

catalog/models/console.py
from django.db import models

class Console(models.Model):
    name = models.CharField(max_length=200, unique=True)
    def __str__(self):
    	return "default" if self.name is None else self.name

catalog/models/game.py
from django.db import models
from .console import Console

class Game(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    available = models.BooleanField(default=True)
    title = models.CharField(max_length=200)
    picture = models.URLField()
    consoles = models.ManyToManyField(Console, related_name='games', blank=True)
    def __str__(self):
    	return self.title

catalog/models/player.py
from django.db import models

class Player(models.Model):
    email = models.EmailField(max_length=100)
    name = models.CharField(max_length=200)
    def __str__(self):
    	return self.name

catalog/models/result.py
from django.db import models
from .game import Game
from .player import Player

class Result(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    score = models.IntegerField(null=True)
    level = models.CharField(max_length=50)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    player = models.ForeignKey(Player, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
    	if 5000 < self.score <= 10000:
        	self.level = 'Advanced'
    	elif self.score > 10000:
        	self.level = 'Expert'
    	else:
    		self.level = 'Beginner'
    	super(Result, self).save(*args, **kwargs)  # Call the "real" save() method.


    def __str__(self):
    	return str(self.score)

catalog/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext as _


class ResultForm(forms.Form):
    score = forms.IntegerField(
        label='Score',
        required=True
        )
    #player = forms.ForeignKey(queryset=Player.objects.all())

    def clean_score(self):
        data = self.cleaned_data['score']
        
        #Check score is not negative. 
        if data < 0 :
            raise ValidationError(_('Invalid score'))

        # Remember to always return the cleaned data.
        return data

catalog/views/addResult.py
from django.http import HttpResponse
from django.template import loader
from django.conf import settings
from django.shortcuts import redirect



def addResult(request):
    if request.user.groups.filter(name='Player'):
        template = loader.get_template('catalog/addResult.html')
    else:
        return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))
    return HttpResponse(template.render(request=request))

catalog/views/detail.py
from django.http import HttpResponse
from django.http import Http404
from catalog.models import Game
from django.template import loader



def detail(request, game_id):
    try:
        game = Game.objects.get(pk=game_id)
        consoles = " ".join([console.name for console in game.consoles.all()])
    except Game.DoesNotExist:
        raise Http404("Game does not exist")
    template = loader.get_template('catalog/detail_game.html')
    context = {
        'game': game,
        'consoles':consoles
    }
    return HttpResponse(template.render(context,request=request))

catalog/views/index.py
from django.http import HttpResponse
from django.http import Http404
from catalog.models import Game
from django.template import loader


def index(request):
    # request games
    try:
        games = Game.objects.filter(available=True).order_by('-created_at')[:3]
    except Game.DoesNotExist:
        raise Http404("Game does not exist")
    template = loader.get_template('catalog/index.html')
    context = {
        'games': games
    }
    return HttpResponse(template.render(context,request=request))

catalog/views/listing.py
from django.http import HttpResponse
from django.http import Http404
from catalog.models import Game
from django.template import loader


def listing(request):
    # request games
    try:
        games = Game.objects.filter(available=True)
    except Game.DoesNotExist:
        raise Http404("Game does not exist")
    template = loader.get_template('catalog/games.html')
    context = {
        'games': games
    }
    return HttpResponse(template.render(context,request=request))

catalog/views/listingResultbyGame.py
from django.http import HttpResponse
from catalog.models import Result
from django.template import loader

def listingResultbyGame(request, game_id):
        results = Result.objects.filter(game=game_id)
        #results = Result.objects.all()
        formatted_results = ["<li>{}</li>".format(result.score) for result in results]
        message = """<ul>{}</ul>""".format("\n".join(formatted_results))
        template = loader.get_template('catalog/resultByGame.html')
        context = {
            'results': results
        }
        return HttpResponse(template.render(context,request=request))

catalog/views/search.py
from django.http import HttpResponse
from catalog.models import Game
import logging


def search(request):
    query = request.GET.get('query')
    if not query:
        games = Game.objects.all()
    else:
        # title contains the query and query is not sensitive to case.
        games = Game.objects.filter(title__icontains=query)

    if not games.exists():
        games = Game.objects.filter(consoles__name__icontains=query)

    if not games.exists():
        message = "Nous n'avons trouvé aucun résultat !"
        logging.error('Something went wrong!')
    else:
        games = ["<li>{}</li>".format(game.title) for game in games]
        message = """
            Nous avons trouvé les jeux correspondant à votre requête ! Les voici :
            <ul>{}</ul>
        """.format("".join(games))

    return HttpResponse(message)

catalog/templates/catalog/addResult.html
{% extends "catalog/base.html" %}

{% block content %}
	<p> Coucou </p>
{% endblock %}

catalog/templates/catalog/base.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% blocktrans%}Games{%endblocktrans %}</title>
    {% load static %}

    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'catalog/css/bootstrap.min.css' %}" />

    <!-- Custom CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'catalog/css/business-casual.css' %}" />


    <!-- jQuery -->
    <script src="{% static 'catalog/js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="{% static 'catalog/js/bootstrap.min.js' %}"></script>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
    {% block title %}
        <div class="brand">{% blocktrans%}Games & fun{% endblocktrans%}</div>
    {% endblock %}

    {% block navbar %}
            <!-- Navigation -->
            <nav class="navbar navbar-default" role="navigation">
                <div class="container">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
                        <a class="navbar-brand" href="index.html">{% blocktrans%}Games & fun{% endblocktrans%}</a>
                    </div>
                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav">
                            <li>
                                <a href="index.html">{% blocktrans%}Home{% endblocktrans%}</a>
                            </li>
                            <li>
                                <a href="about.html">{% blocktrans%}About{% endblocktrans%}</a>
                            </li>
                            <li>
                                <a href="{% url 'catalog:list' %}">{% blocktrans%}All games{% endblocktrans%}</a>
                            </li>
                            <li>
                                <a href="contact.html">{% blocktrans%}Connect{% endblocktrans%}</a>
                            </li>
                        </ul>
                    </div>
                    <!-- /.navbar-collapse -->
                </div>
                <!-- /.container -->
            </nav>
    {% endblock %}

    <div id="content">
        {% block content %}{% endblock %}
    </div>

    </body>

</html>

catalog/templates/catalog/detail_game.html
{% extends "catalog/base.html" %}
{% load i18n %}
    {% block title %}
        <div class="brand">{% blocktrans%}{{game}}{% endblocktrans%}</div>
    {% endblock %}

    {% block content %}

<p>{{game}}</p>
<p>{{consoles}}</p>

		
	{% endblock %}

catalog/templates/catalog/games.html
{% extends "catalog/base.html" %}
{% load i18n %}
    {% block title %}
        <div class="brand">{% blocktrans%}Games list{% endblocktrans%}</div>
    {% endblock %}

    {% block content %}

	<table
  data-toggle="table"
  data-search="true"
  data-show-columns="true">
  <thead>
    <tr class="tr-class-1">
      <th data-field="name" rowspan="2" data-valign="middle">{% blocktrans%}Name{% endblocktrans%}</th>
      <th>{% blocktrans%}Detail{% endblocktrans%}</th>
      <th>{% blocktrans%}Description{% endblocktrans%}</th>
	  <th>{% blocktrans%}Consoles{% endblocktrans%}</th>
	  <th>{% blocktrans%}Actions{% endblocktrans%}</th>
    </tr>
  </thead>
  <tbody>
	{% for game in games %}
    <tr>
      <td><a href="{% url 'catalog:detail' game.id  %}">{{game.title}}</a></td>
      <td style="width: 10%" ><img class="card-img-top" src="{{ game.picture }}" alt="Card image cap"></td>
      <td>Bla bla bla</td>
	  <td>{{ game.consoles.all.0 }}</td>
	  <td><a href="{% url 'catalog:listresult' game.id %}">{% blocktrans%}Display results{% endblocktrans%}</a></td>
    </tr>
	{% endfor %}
  </tbody>
</table>

		
	{% endblock %}

catalog/templates/catalog/index.html
{% extends "catalog/base.html" %}
{% load i18n %}

{% block content %}


    <div class="container">


        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">{% blocktrans%}Welcome on Games & fun{% endblocktrans%}</h2>
                    <hr>
                    <hr class="visible-xs">
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vestibulum mattis ullamcorper velit sed ullamcorper. Tellus mauris a diam maecenas sed enim ut sem. Nisi vitae suscipit tellus mauris a diam maecenas sed. Facilisis gravida neque convallis a cras semper. In pellentesque massa placerat duis ultricies lacus sed. Ac placerat vestibulum lectus mauris. Pulvinar sapien et ligula ullamcorper malesuada proin libero nunc. Dignissim convallis aenean et tortor at risus viverra adipiscing. Sed risus pretium quam vulputate. Lectus arcu bibendum at varius vel pharetra vel turpis nunc.</p>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="box">
                <div class="col-6">
                    <hr>
                    <h2 class="intro-text text-center">{% blocktrans%}3 last games{% endblocktrans%}
                    </h2>
                    <hr>
                    {% block lastgames %}

                        {% include 'catalog/list.html' %}

                    {% endblock %}
                </div>
            </div>
            <div class="box">
                <div class="col-6">
                    <hr>
                    <h2 class="intro-text text-center">{% blocktrans%}3 best scores{% endblocktrans%}
                    </h2>
                    <hr>
                    {% block bestscores %}

                        {% include 'catalog/list.html' %}

                    {% endblock %}
                </div>
            </div>
        </div>

    </div>


{% endblock %}

catalog/templates/catalog/list.html
<ul>
{% for game in games %}
    <li><a href="{% url 'catalog:detail' game.id  %}">{{game.title}}</a></li></li>
{% endfor %}
</ul>

catalog/templates/catalog/resultByGame.html
{% extends "catalog/base.html" %}
{% load i18n %}
    {% block title %}
    	{% for result in results %}
        <div class="brand">Results for {{result.game}} </div>
        {% endfor %}
			
    {% endblock %}

        {% block content %}			
		
		<table
		data-toggle="table"
		data-search="true"
		data-show-columns="true">
		<thead>
		  <tr class="tr-class-1">
			<th data-field="name" rowspan="2" data-valign="middle">{% blocktrans%}Name{% endblocktrans%}</th>
			<th>{% blocktrans%}Detail{% endblocktrans%}</th>
			<th>{% blocktrans%}Description{% endblocktrans%}</th>
			<th>{% blocktrans%}Consoles{% endblocktrans%}</th>
			<th>{% blocktrans%}Actions{% endblocktrans%}</th>
		  </tr>
		</thead>
		<tbody>
		  {% for game in games %}
		  <tr>
			<td><a href="{% url 'catalog:detail' game.id  %}">{{game.title}}</a></td>
			<td style="width: 10%" ><img class="card-img-top" src="{{ game.picture }}" alt="Card image cap"></td>
			<td>Bla bla bla</td>
			<td>{{ game.consoles.all.0 }}</td>
			<td><a href="{% url 'catalog:listresult' game.id %}">{% blocktrans%}Display results{% endblocktrans%}</a></td>
		  </tr>
		  {% endfor %}
		</tbody>
	  </table>


			{% for result in results %}
			    <p>{{result.player}} : {{result.game}} // {{result.score}}</p>

			{% endfor %}


			<a href="{% url 'catalog:addResult' %}" class="btn btn-primary">{% blocktrans%}Add a result{% endblocktrans%}</a>
			
		{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Games</title>
    {% load static %}

    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'catalog/css/bootstrap.min.css' %}" />

    <!-- Custom CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'catalog/css/business-casual.css' %}" />


    <!-- jQuery -->
    <script src="{% static 'catalog/js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="{% static 'catalog/js/bootstrap.min.js' %}"></script>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
    {% block title %}
        <div class="brand">Games & fun</div>
    {% endblock %}

    {% block navbar %}
            <!-- Navigation -->
            <nav class="navbar navbar-default" role="navigation">
                <div class="container">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
                        <a class="navbar-brand" href="index.html">Games & fun</a>
                    </div>
                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav">
                            <li>
                                <a href="index.html">Home</a>
                            </li>
                            <li>
                                <a href="about.html">About</a>
                            </li>
                            <li>
                                <a href="{% url 'catalog:list' %}">All games</a>
                            </li>
                            <li>
                                <a href="contact.html">Connect</a>
                            </li>
                        </ul>
                    </div>
                    <!-- /.navbar-collapse -->
                </div>
                <!-- /.container -->
            </nav>
    {% endblock %}

    <div id="content">
        {% block content %}{% endblock %}
    </div>

    </body>

</html>